
name: Lint the code

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Lint python code
    runs-on: ubuntu-latest
      strategy:
        matrix:
          python-version: [3.9]
          
      steps: 
        - name: checkout 
          uses: actions/checkout@v2
        - name: setting up Python ${{ matrix.python-version }}
          uses: actions/setup-python@v2
          with:
            python-version: ${{ matrix.python-version }}
          
      - name: Dependencies 
        run: |
          python -m pip install --upgrade pip
          pip install flake8
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          
      - name: Lint the code
        run: |
          # check for syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
